### ISSUE TITLE
Suggestion: Global shortcut for tweeting a song

### ISSUE THREAD

**Issue by neet** [kPherox/NowPlayingTweet#1]
Hi, thanks for developing this app. I think it's an awesome app and I love this!

However, it doesn't have global shortcut feature. Some other similar app such as [TunesTweet](http://kindadev.com/blog/?p=911) has this feature and I have been using it so far.

If the feature will be included, this app would be nice more 👍

**Comment by kphrx** [comment]
Thanks for the suggestion.
It will be added in the new release.
