### ISSUE TITLE
"One of the uploaded media is too large"

### ISSUE THREAD

**Issue by hibiyasleep** [kPherox/NowPlayingTweet#9]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/5380174/55300377-21b49b00-5472-11e9-9e59-8ffaf91ef72c.png">

> $ identify ~/Music/.../jacket_disc_3.jpg
> ... JPEG 1400x1400 1400x1400+0+0 8-bit sRGB 2.30783MiB 0.000u 0:00.000

> $ ffprobe ~/Music/.../3.04 ...m4a
> Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 1400x1400, 90k tbr, 90k tbn, 90k tbc

I can't figure out why this happens, since this albumart is only 2.3MiB, and TweetDeck (which don't resize) uploads .jpg file without any problem.

Here's sample file:
* [3.05 Affection (Extended mix).m4a](https://d.hibiya.moe/nqP.m4a) 
* [jacket_disc_3.jpg](https://d.hibiya.moe/68a.jpg)

**Comment by kphrx** [comment]
Thanks reporting the issue.

This bug has been fixed in #11. This change is included in version 0.5.1 :)
